version: "3"
services:
  web:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - ./frontend/.env
    depends_on: 
      - back
  back:
    build: ./backend
    ports:
      - "5000:8080"
    restart: always
    env_file:
      - ./backend/.env
