version: "3"
services:
  web:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - ./frontend/.env
    depends_on:
      - back

  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    env_file:
      - ./nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on: 
      - web

  back:
    build: ./backend
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file:
      - ./backend/mongodb.env
    ports:
      - 27017:27017

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes: 
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro


volumes:
  nginx_secrets:
