sudo: true
dist: xenial
language: python
python:
- 3.6
cache: pip
addons:
  apt:
    packages:
      - libglib2.0-0
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libglib2.0-0 libsm6 libxrender1 libfontconfig1
install:
- pip install -r requirements.txt
- pip install .
before_script:
- pip install nose coverage
- pip install coveralls
script:
- python3 setup.py nosetests --with-coverage --cover-package fer --verbosity=2
after_success:
- coveralls
deploy:
  provider: pypi
  user: jshenk
  skip_cleanup: true
  skip_existing: true
  on:
    tags: true
    branch: master
  password:
    secure: Fmc7BLmn+M4jGu3s6w+gMfEDcHx348ZIPLS94Jt7UBWhPVy5qCu+tr2/a/Oak3wvzJfixmx9it9o4ti0UKFXRQNeMVFQVj72OjDzU7YX6gnfNLYhaT8Ip+LyrCdvTUPvHbaNy0R4Y7O3HJrgBekz2A0bPji9Xk6Aqhti2JevjxLWKuwmgubLwHW4rCutfxJoO6wi+t5mU1EhjIqW6/8MA9I8F2DxIs1bHGGgyHRfo74zBkkaWacMsfmlppHg+nsI2RQUWe/Yud4DDoFgbE+y0xW0ftsInGp6gyz0bczA0MxxU46mVmG/ZoE2/b95oKdbBa9p5d3Y4IOhmxaych5Nwq6gufZFNPfhtna6iPiuq5HdN4sslQn4wDglXXpA6Q6IwnBOPpy0STmDP6QJub7JUkRlykNqRPElm7AxgKEYkMnksuaywSSF6ATJTZllKmsZxWTUhuWmLTkk67gExOhOWH3sAHceNG7wTAwk9rLWE4feR1QdnJMG3xyWxqhl2FoAq03WyM72KRu04M0y0AI/9A30mD0BaEii6cWcq56yrtHB5HN5sTy0b2jqcexiOsa0hBzczIWM3uiz2BHR8jJ5O5sw0u1MuMeVqefPXbe1xch/oyocjU5Z90VMsK1p9rk9QcyP3wY+bRN/dlZAFNQvSSzf/vOCy4J4oJ1/nKZKVWI=
