language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libglib2.0-0 libsm6 libxrender1 libfontconfig1
install:
  - pip install -r requirements.txt
  - pip install nose coverage
  - pip install coveralls
  - pip install tensorflow
# # command to run tests, e.g. python setup.py test
script:
  - python3 setup.py nosetests --with-coverage --cover-package mtcnn --verbosity=2
after_success:
  - coveralls
